# ==============================
# HACKER / CRT HYPRTOOLKIT THEME
# ==============================

background = rgba(8, 11, 9, 0.96)

accent = rgba(0, 255, 102, 1.0)
accent_secondary = rgba(22, 77, 44, 1.0)

font_family = JetBrainsMono Nerd Font
font_family_monospace = JetBrainsMono Nerd Font

small_font_size = 12

radius = 0
