background {
    monitor =
    color = rgba(080b09ff)
}

input-field {
    monitor =
    size = 300, 60
    outline_thickness = 1
    outer_color = rgba(00ff66ff)
    inner_color = rgba(080b09ff)
    font_color = rgba(c8ffd8ff)
    placeholder_text = Password...
    check_color = rgba(00ff66ff)
    fail_color = rgba(ff5555ff)
}

label {
    monitor =
    text = $TIME
    color = rgba(00ff66ff)
    font_size = 48
    position = 0, 100
    halign = center
    valign = center
}
