general {
    gaps_in = 4
    gaps_out = 8

    border_size = 1

    col.active_border = rgb(00ff66)
col.inactive_border = rgb(163d24)

    layout = dwindle
}

decoration {
    rounding = 0

    active_opacity = 1.0
    inactive_opacity = 0.92

    shadow {
        enabled = true
        range = 8
        render_power = 2
    }
}

animations {
    enabled = true

    bezier = hacker, 0.05, 0.9, 0.1, 1.0

    animation = windows, 1, 3, hacker
    animation = windowsOut, 1, 3, hacker
    animation = border, 1, 3, hacker
    animation = fade, 1, 3, hacker
    animation = workspaces, 1, 3, hacker
}
exec-once = touch /tmp/hyprland-startup-test
bind = SUPER, B, exec, flatpak run net.waterfox.waterfox
